-   name: Install Packages
    apt:
        pkg:
        -   docker-compose

-   name: Join docker group
    user:
        name: '{{ ansible_env.SUDO_USER }}'
        groups: docker
        append: yes

-   name: Create directory
    file:
        path: '{{item}}'
        state: directory
        mode: '0755'
    with_items:
    -   /data
    -   /home/{{ansible_env.SUDO_USER}}/service

-   name: Fetch Harbor installer
    unarchive:
        src: https://github.com/goharbor/harbor/releases/download/v2.4.3/harbor-online-installer-v2.4.3.tgz
        dest: /home/{{ansible_env.SUDO_USER}}/service
        remote_src: yes

-   name: Place Harbor config
    template:
        src: harbor/harbor.yml.j2
        dest: /home/{{ansible_env.SUDO_USER}}/service/harbor/harbor.yml

-   name: Checking docker-compose.yml existence
    stat:
        path: /home/{{ansible_env.SUDO_USER}}/service/harbor/docker-compose.yml
    register: docker_compose

-   name: Install Harbor
    shell: /home/{{ansible_env.SUDO_USER}}/service/harbor/install.sh
    when: not docker_compose.stat.exists

-   name: Install harbor.service
    template:
        src: harbor/harbor.service.j2
        dest: /etc/systemd/system/harbor.service
    notify: enable harbor service

-   name: Start Harbor
    docker_compose:
        project_src: /home/{{ansible_env.SUDO_USER}}/service/harbor/
        restarted: yes
    register: output

-   name: Display result
    debug:
        var: output
