-   name: reload sysctl
    shell: sysctl --system

-   name: restart kubelet
    service:
        name: kubelet
        state: restarted

-   name: reload mount
    shell: mount -a

-   name: reboot
    reboot:
        reboot_timeout: 300

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
