-   name: reload udev rules
    shell: udevadm control --reload-rules
    listen: reload udev

-   name: trigger udev
    shell: udevadm trigger
    listen: reload udev

-   name: restart nut-server
    service:
        name: nut-server
        state: restarted

-   name: restart nut-client
    service:
        name: nut-client
        state: restarted
